version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: servicedb
      MYSQL_USER: bindisha
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
    volumes:
      - mysql_data:/var/lib/mysql  

  springboot-app:
 #   build: .
    image : bindisha/couponservicerepo:v1
    container_name: springboot-container
    ports:
      - "9091:9091"
    environment:
      DB_HOST: mysql-docker
      DB_PORT: 3306
      DB_NAME: servicedb
      DB_USER: bindisha
      DB_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:
     external: true

volumes:
  mysql_data:
